<?php 

function neighborly_register() {
  echo '
        <form id="address">
          <label>Enter your address</label>
          <input value="" />
          <div class="description">
            to see your neighborly neighbors
          </div>
        </form>
  ';
}


function neighborly_tiles($region = array(0,0,0,0), $scale = 100, $quantity = 10) {

  echo "tiles tiles tiles tiles tiles tiles tiles tiles tiles tiles tiles tiles tiles tiles tiles tiles tiles tiles tiles tiles tiles tiles tiles tiles tiles tiles tiles tiles tiles tiles tiles tiles tiles tiles tiles tiles tiles tiles tiles tiles tiles tiles tiles tiles tiles tiles tiles tiles tiles tiles tiles tiles";
}
?>